version: '1'

services:
  mysql:
    image: mysql
    networks:
      - network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "3305:3306"
    restart: always
    mem_limit: 1024m
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  app:
    image: reliable-kku-server:1.0.0
    networks:
      - network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    restart: always
    mem_limit: 1024m
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/deundeun?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - network
    ports:
      - "9090:9090"
    depends_on:
      - app
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    networks:
      - network
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

networks:
  network:
    driver: bridge