spring:
  profiles:
    default: local
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: root
  jpa:
    open-in-view: false
  config:
    import:
      - submodule/reliable-kku-server-submodule/application-s3.yaml
      - submodule/reliable-kku-server-submodule/application-jwt.yaml
      - submodule/reliable-kku-server-submodule/application-payment.yaml
      - submodule/reliable-kku-server-submodule/application-sms.yaml

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
